# Generated by Django 6.0.6 on 2026-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('element', models.CharField(choices=[('P', 'Pyro'), ('H', 'Hydro'), ('E', 'Electro'), ('G', 'Geo'), ('C', 'Cryo'), ('D', 'Dendro'), ('L', 'Lunar'), ('S', 'Stellar')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('weapon_type', models.CharField(choices=[('SW', 'Sword'), ('CL', 'Claymore'), ('PL', 'Polearm'), ('BW', 'Bow'), ('CT', 'Catalyst')], max_length=2)),
                ('region', models.CharField(choices=[('MO', 'Mondstadt'), ('LI', 'Liyue'), ('IN', 'Inazuma'), ('SU', 'Sumeru'), ('FO', 'Fontaine'), ('NA', 'Natlan'), ('NK', 'Nod Krai'), ('SN', 'Snezhnaya')], max_length=2)),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='characters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['name'],
            },
        ),
    ]
