# Generated by Django 6.0.6 on 2026-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charinfo',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
