# Generated by Django 6.0.6 on 2026-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genshin', '0002_alter_charinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
